#' @title Copy a list of files on the system
#' @description Copy a list of files on the system.
#' @param file_list A character vector of file names (without extensions).
#' @param extension The extension to apply to file names.
#' @param path The path to the origin directory containing the files to copy.
#' @param new_path The path to the destination directory. If it doesn't exist,
#' this directory will be created (recursively).
#' @return Nothing.
system_cp_files <- function(file_list, extension, path, new_path) {
  fs::dir_create(new_path)
  purrr::walk(
    .x = file_list,
    .f = function(x) {
      file_path <- fs::path(path, paste0(x, extension))
      file_new_path <- fs::path(new_path, paste0(x, extension))
      fs::file_copy(
        path = file_path,
        new_path = file_new_path,
        overwrite = TRUE
      )
    }
  )
}

#' @title Copy profile HMM files from one directory to another
#' @description Copy profile HMM files from one directory to another.
#' @param hmm_list A character vector listing HMM file names to be copied, such
#' as that generated by...
#' @param path The path to
#' @param new_path asd...
#' @return Nothing.
#' @export
system_cp_hmm <- function(hmm_list, path, new_path) {
  system_cp_files(hmm_list, ".hmm", path, new_path)
}

#' @title Copy system description files from one directory to another
#' @description Copy system description files from one directory to another.
#' @param sys_list A character vector listing system description file names to
#' be copied, such as that generated by...
#' @param path The path to
#' @param new_path asd...
#' @return Nothing.
#' @export
system_cp_sys <- function(sys_list, path, new_path) {
  system_cp_files(sys_list, ".yaml", path, new_path)
}
